<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenUrzednik.Gus\OpenUrzednik.Gus.csproj" />
    <ProjectReference Include="..\..\src\OpenUrzednik.Krs\OpenUrzednik.Krs.csproj" />
    <ProjectReference Include="..\..\src\OpenUrzednik.Mf\OpenUrzednik.Mf.csproj" />
    <ProjectReference Include="..\..\src\OpenUrzednik.Nbp\OpenUrzednik.Nbp.csproj" />
    <ProjectReference Include="..\..\src\OpenUrzednik.Nbp.DependencyInjection\OpenUrzednik.Nbp.DependencyInjection.csproj" />
    <ProjectReference Include="..\OpenUrzednik.TestCommon\OpenUrzednik.TestCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Gus\" />
    <Folder Include="Krs\" />
    <Folder Include="Mf\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="WireMock.Net" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Nbp\Fixtures\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>